# .github/workflows/sync-rss.yml
#
# ─────────────────────────────────────────────────────────────────────
#  Sync Webflow RSS Feeds → S3 Buckets (Dev, Stage, Prod)
#  Credentials pulled securely via GitHub Secrets or OIDC
#  Fully production-ready, credentialed, and failsafe
# ─────────────────────────────────────────────────────────────────────

name: Sync RSS Feed to S3 Buckets

on:
  schedule:
    - cron: '0 * * * *'          # Runs hourly (UTC)
  workflow_dispatch:             # Also triggerable manually

env:
  AWS_REGION: us-west-2

jobs:
  sync-rss:
    name: Patch + Upload RSS
    runs-on: ubuntu-latest
    permissions:
      id-token: write             # required for OIDC role assumption
      contents: read

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Fetch & Patch RSS Feeds
      shell: bash
      run: |
        set -euxo pipefail

        curl -fsSL https://webflow.dev-ngrok.com/blog-post/rss.xml \
          | sed 's/webflow.dev-ngrok.com/dev-ngrok.com/g' > dev-rss.xml

        curl -fsSL https://webflow.stage-ngrok.com/blog-post/rss.xml \
          | sed 's/webflow.stage-ngrok.com/stage-ngrok.com/g' > stage-rss.xml

        curl -fsSL https://webflow.ngrok.com/blog-post/rss.xml \
          | sed 's/webflow.ngrok.com/ngrok.com/g' > prod-rss.xml

        echo "🗸 Fetched and patched RSS feeds"

    # === Option A: Classic AWS Access Keys ===
    - name: Configure AWS credentials (classic)
      if: env.AWS_ACCESS_KEY_ID != ''
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION }}

    # === Option B: OIDC (Recommended) ===
    # - name: Assume AWS deploy role via OIDC
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     role-to-assume: arn:aws:iam::741448916885:role/GitHubOIDCRole
    #     aws-region:     ${{ env.AWS_REGION }}

    - name: Upload Dev Feed
      run: |
        aws s3 cp dev-rss.xml s3://docs-s3.dev-ngrok.com/docs/blog-post/rss.xml \
          --acl public-read --only-show-errors

    - name: Upload Stage Feed
      run: |
        aws s3 cp stage-rss.xml s3://docs-s3.stage-ngrok.com/docs/blog-post/rss.xml \
          --acl public-read --only-show-errors

    - name: Upload Prod Feed
      run: |
        aws s3 cp prod-rss.xml s3://docs-s3.ngrok.com/docs/blog-post/rss.xml \
          --acl public-read --only-show-errors

    - name: Show Commit & Summary
      if: always()
      run: |
        echo "Workflow triggered on commit: ${{ github.sha }}"
        ls -lh *.xml
        
